/// Note Model - Data class representing a single voice note
/// 
/// This is the core data structure for the Voice Notes Plus application.
/// Each Note instance represents a complete voice recording with metadata.
///
/// Features:
///   - Unique identification via dynamic id (generated by Hive)
///   - Customizable title for easy reference
///   - Speech-to-text generated transcript content
///   - Automatic timestamp recording
///   - Tag-based categorization (comma-separated)
///   - Like/favorite marking for quick filtering
///   - Path to original audio recording file
///
/// All fields are immutable (final) to ensure data consistency.
/// Use factory constructors to create instances from database maps.
class Note {
  /// Unique identifier for the note in database
  /// Type: dynamic because Hive auto-assigns unique ids
  /// Used as primary key for database operations
  final dynamic id;
  
  /// User-defined or auto-generated title for the note
  /// Displayed in home screen list and detail view header
  /// Can be empty string for untitled notes
  final String title;
  
  /// Complete speech-to-text transcript of the voice recording
  /// Primary content of the note - generated by speech_to_text plugin
  /// Displayed in detail screen with selection capability
  final String content;
  
  /// Timestamp when the note was created
  /// Format: "YYYY-MM-DD HH:MM:SS" (formatted in add_note_screen.dart)
  /// Displayed in note detail view metadata header
  final String dateTime;
  
  /// Comma-separated category tags for organizing notes
  /// Examples: "work,important", "personal,grocery", "project-alpha,urgent"
  /// Displayed as chips in detail screen header
  /// Filterable from home screen search
  /// Default: empty string if no tags provided
  final String tags;
  
  /// Boolean flag indicating if note is marked as favorite/liked
  /// Used for quick filtering on home screen (_showLikedOnly toggle)
  /// Displayed with heart icon in home screen list and detail view
  /// Can be toggled via heart icon button in detail view
  /// Default: false for new notes
  final bool isLiked;
  
  /// File path to the original audio recording
  /// Points to the .wav or audio file generated during recording
  /// Used for potential future playback functionality
  /// Currently stored but not actively used in UI
  /// Default: empty string if no recording saved separately
  final String recordingPath;

  /// Constructor for creating a Note instance
  /// 
  /// Parameters:
  ///   - id: Auto-assigned by Hive (optional, null initially)
  ///   - title: REQUIRED - User-provided or generated title
  ///   - content: REQUIRED - Complete transcript text
  ///   - dateTime: REQUIRED - Timestamp of creation
  ///   - tags: Optional, defaults to empty string
  ///   - isLiked: Optional, defaults to false (not liked)
  ///   - recordingPath: Optional, defaults to empty string
  Note({
    this.id,
    required this.title,
    required this.content,
    required this.dateTime,
    this.tags = '',
    this.isLiked = false,
    this.recordingPath = '',
  });

  /// ====== SERIALIZATION METHODS ======
  
  /// Convert Note instance to Map for database storage
  /// 
  /// Converts all note fields into a key-value map structure
  /// Required by Hive database to serialize objects before storing
  /// 
  /// Usage:
  ///   - Called internally by DatabaseHelper.addNote()
  ///   - Called internally by DatabaseHelper.updateNote()
  ///   - Prepares data for Hive box.put() and box.update() operations
  ///
  /// Return value:
  ///   - Map<String, dynamic> with all note fields as key-value pairs
  ///   - Keys must match database schema: 'id', 'title', 'content', etc.
  ///
  /// Example:
  ///   Note myNote = Note(...);
  ///   Map data = myNote.toMap();
  ///   // Result: {'id': null, 'title': 'My Note', 'content': '...', ...}
  Map<String, dynamic> toMap() {
    return {
      'id': id,
      'title': title,
      'content': content,
      'dateTime': dateTime,
      'tags': tags,
      'isLiked': isLiked,
      'recordingPath': recordingPath,
    };
  }

  /// ====== DESERIALIZATION ======
  
  /// Factory constructor to create Note instance from database Map
  /// 
  /// Converts a Map retrieved from Hive database into a Note object
  /// Provides null-safety with default values for missing or null fields
  /// Required for reconstructing objects after database retrieval
  ///
  /// Usage:
  ///   - Called by DatabaseHelper._getNotesList() for each note in database
  ///   - Called after Hive box.getAt() or box.values operations
  ///   - Essential for converting raw database data into typed objects
  ///
  /// Null-Safety Strategy:
  ///   - String fields default to '' (empty string) if missing/null
  ///   - Boolean fields default to false if missing/null
  ///   - id field can remain null (assigned by Hive on first save)
  ///   - Prevents crashes from incomplete or corrupted database records
  ///
  /// Parameters:
  ///   - map: Map<String, dynamic> from Hive database containing note data
  ///
  /// Return value:
  ///   - New Note instance with all fields populated
  ///   - Safe defaults applied to null or missing values
  ///
  /// Example:
  ///   Map dbData = {'id': 1, 'title': 'My Note', 'content': '...', ...};
  ///   Note restoredNote = Note.fromMap(dbData);
  ///   // Result: Note with all fields populated safely
  factory Note.fromMap(Map<String, dynamic> map) {
    return Note(
      id: map['id'],
      title: map['title'] ?? '',
      content: map['content'] ?? '',
      dateTime: map['dateTime'] ?? '',
      tags: map['tags'] ?? '',
      isLiked: map['isLiked'] ?? false,
      recordingPath: map['recordingPath'] ?? '',
    );
  }
}
